### ISSUE TITLE
Implement the `OpticalDataPropositionInput` `not`

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/database#52] opened 2023-11-30 15:27 UTC
When I query https://www.solarbuildingenvelopes.com/graphql/ with
```
query {
  byNegation: allData(
    where: { not: { gValues: { some: { greaterThanOrEqualTo: 0.5 } } } }
  ) {
    edges {
      node {
        uuid
      }
    }
  }
}
```
I receive
```
{
  "errors": [
    {
      "message": "The specified input object field `not` does not exist.",
      "locations": [
        {
          "line": 3,
          "column": 14
        }
      ],
      "path": [
        "byNegation"
      ],
      "extensions": {
        "field": "not",
        "specifiedBy": "http://spec.graphql.org/October2021/#sec-Input-Object-Field-Names"
      }
    }
  ]
}
```
because `not` isn't part of [type-defs.graphqls)](https://github.com/building-envelope-data/database/blob/edb27df1a6feb251dd85381d6e219caee6a11c9f/frontend/type-defs.graphqls).

**Comment by simonwacker** [comment] 2024-09-24 15:58
I close this issue as it is a domain-specific duplicate of https://github.com/building-envelope-data/database/issues/17

**Closed as completed by simonwacker** 2024-09-24 15:58 UTC
Labels: ISE
